config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'logs/index'
  get 'logs/show'
  get 'users/index'
  get 'users/show'
  devise_for :users


  resources :users, only: [:index, :show]
  resources :logs, only: [:index, :show, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end

  #welcomepage作る
  root 'welcome#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :log
  belongs_to :user
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user, dependent: :destroy, optional: true
  belongs_to :target, optional: true
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
end

app/models/target.rb
class Target < ApplicationRecord
    has_many :users, dependent: :destroy
    has_many :logs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :logs, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_logs, through: :likes, source: :log





  def already_liked?(log)
    self.likes.exists?(log_id: log.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        added_auth = [:name, :email, :password, :password_confirmation]
        devise_parameter_sanitizer.permit :sign_up, keys: added_auth
        devise_parameter_sanitizer.permit :account_update, keys: added_auth
        devise_parameter_sanitizer.permit :account_update, keys: added_auth
             

    end

end

  

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.create(log_id: params[:log_id])
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        @like = Like.find_by(log_id: params[:log_id], user_id: current_user.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

  #Auth前では操作できないように
  before_action :authenticate_user!, only: [:create]
  before_action :edit_delete_user, only: [:edit, :update, :destroy]

  def index
    @logs = Log.all
    @log = Log.new
  end

  def show
    @log = Log.find(params[:id])
    @like = Like.new
  end

  def edit
    @log = Log.find(params[:id])
  end

  def destroy
    log = Log.find(params[:id])
    log.delete
  end


  def create
    @log = Log.new(log_params)
    @log.user_id = current_user.id
    if @log.save
      flash.notice = '送信しました。'
      redirect_back(fallback_location: root_path)
    else
      flash.now.alert = 'エラー'
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def log_params
    params.require(:log).permit(:brealfast, :lunch, :dinner, :comment)
  end

  def edit_delete_user
    unless Log.find(params[:id]).user.id.to_i == current_user.id
        redirect_to logs_path(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meal share app</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">Meal share app</h5>
    <nav class="my-2 my-md-0 mr-md-3">

    <%if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
      <%= link_to "My page", user_path(current_user.id) %>
      <a class="btn btn-outline-primary" href="/users/">Users</a>
      <a class="btn btn-outline-primary" href="/logs/">Logs</a>
    <% end %>
    </nav>

  </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/logs/index.html.erb
<div class="container">
  <h1>Logs</h1>
  <hr class="my-4">

  <%if user_signed_in? %>
    <div class="py-5 text-center">
    <h2>投稿する</h2>

          <%= form_for @log do |form| %>
          <div class="field">
            <%= form.label :breakfast %>
            <%= form.text_field :brealfast %>
          </div>

          <div class="field">
            <%= form.label :lunch %>
            <%= form.text_field :lunch %>
          </div>

          <div class="field">
            <%= form.label :dinner %>
            <%= form.text_field :dinner %><br>
          </div>


          <div class="field">
            <%= form.label :comment %>
            <%= form.text_field :comment %>
          </div>

        
          <%= form.submit %>
          
          <% end %>
    </div>

    <hr class="my-4">
    <div class="py-5 text-center">
      <h3>投稿一覧</h3>
      
      <% @logs.each do |log| %>
        <a href="/users/<%= log.user.id %>"><%= log.user.name %></a>
        (<%= log.liked_users.count %>)
      <br>
      <% end %>
    </div>


  <% else %>
    <%= link_to "Registration", new_user_registration_path %><br>
    <%= link_to "Log in", new_user_session_path %>
  <% end %>
</div>

app/views/logs/show.html.erb
<div class="container">
<h1>投稿詳細ページ</h1>
<h3><%= @log.user.name %></h3>
<hr class="my-4">
<tr>
    <div class="my-3 ml-3">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>User</th>
                    <th>brealfast</th>
                    <th>lunch</th>
                    <th>dinner</th>
                    <th>Likecount</th>
                    <th>Comment</th>
                </tr>
            </thead>
            <tbody>
                    <tr>
                        <td><%= @log.user.name %></td>
                        <td><%= @log.brealfast %></td>
                        <td><%= @log.lunch %></td>
                        <td><%= @log.dinner %></td>
                        <td><%= @log.likes.count %></td>
                        <td><%= @log.comment %></td>
                    </tr>
            </tbody>
        </table>
    </div>
</tr>

<% if current_user.already_liked?(@log) %>
    <h3>Like: <%= @log.likes.count %></h3>
    
    <%= button_to 'Cancel', log_like_path(@log), method: :delete %>
<% else %>
    
    <%= button_to 'Like', log_likes_path(@log) %>

<% end %>

<h3>Likeしたユーザー</h3>
<% @log.liked_users.each do |user| %>
  <li><%= user.name %></li>
<% end %>

<%= link_to "Back", logs_path %>

</div>

app/views/users/index.html.erb
<div class="container">
<h1>Users</h1>

<%if user_signed_in? %>


  <% @users.each do |user| %>
    <a href="/users/<%= user.id %>"><%= user.name %></a>
    <hr>
  <% end %>
<%= link_to "Back", logs_path %>

<% else %>
  <%= link_to "Registration", new_user_registration_path %><br>
  <%= link_to "Log in", new_user_session_path %>
<% end %>
<div>

app/views/users/show.html.erb
<div class="container">
<div class="py-5 text-center">
<h1>User</h1>
<hr class="my-4">
<h3>Username:<%= @user.name %></h3>
<hr class="my-4">
<h3>投稿内容</h3>
<tr>
    
    <div class="my-3 ml-3">
        <table class="table-bordered">
            <thead>
                <tr>
                    <th>breakfast</th>
                    <th>lunch</th>
                    <th>dinner</th>
                    <th>Likecount</th>
                    <th>#</th>
                    <th>#</th>
                </tr>
            </thead>

            <tbody>
                <% @user.logs.each do |log| %>
                    <tr>
                        <td><%= log.brealfast %></td>
                        <td><%= log.lunch %></td>
                        <td><%= log.dinner %></td>
                        <td><%= log.likes.count %></td>
                        <td><%= link_to 'Show', log %></td>
                        <td><%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %></td>
                    </tr>
                <%end%>
            </tbody>
        </table>
    <div>
</tr>
</div>
<%= link_to "ユーザー一覧へ", users_path %>
<%= link_to "ホームへ戻る", logs_path %>
</div>

app/views/welcome/index.html.erb
<div class="container">
<h1>Welcome Meal share app</h1>
<img class="d-block mx-auto mb-4">
 <%= image_tag "https://1.bp.blogspot.com/-HyIFKnT4YUs/WGYi4WrfPlI/AAAAAAABAu0/MkBHhYM3C4MwZEP5qTgPzRqIauWQ7Iw7wCLcB/s800/character_food_gohan.png",height:"144" %>

<% if user_signed_in? %>
  <p>You are <%= current_user.name %></p>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>
</div>